
import {Poppins} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import {Layout} from "antd";
import Head from 'next/head'
import {Metadata, Viewport} from "next";

const poppins = Poppins({subsets: ["latin"], weight: ["300", "400", "500", "600", "700"]});

export const metadata: Metadata = {
    title: "Bulldog",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    width: 'device-width',
    height: 'device-height',
    initialScale: 1.0,
    userScalable: false,
    themeColor:'#000'
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link rel="prefetch" href="https://github.com/siinaheidari/test/raw/main/public/assets/videos/introBull.mp4" as="video" type="video/mp4"/>
            <link rel="prefetch" href="https://github.com/siinaheidari/test/raw/main/public/assets/videos/mosa.mp4" as="video" type="video/mp4"/>
            <link rel="prefetch" href="https://github.com/siinaheidari/test/raw/main/public/assets/videos/parsafar.mp4" as="video" type="video/mp4"/>
        </head>
        <body className={poppins.className + " !min-h-[calc(100dvh)]"}>

        <video preload={"auto"} className={"bg-cover object-cover !h-screen !size-full hidden"}  autoPlay muted playsInline loop
               controls={false}>
            <source src="https://github.com/siinaheidari/test/raw/main/public/assets/videos/introBull.mp4" type="video/mp4"/>
        </video>

        <Providers>
            <Layout className={'!min-h-[calc(100dvh)] text-white'}>
                {children}
            </Layout>
        </Providers>
        </body>
        </html>
    );
}
