import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import {Layout} from "antd";


const poppins = Poppins({subsets: ["latin"], weight: ["300", "400", "500", "600", "700"]});

export const metadata: Metadata = {
    title: "Bulldog",
    description: "Generated by create next app",
    viewport:"width=device-width, initial-scale=1, maximum-scale=1",
    themeColor:"#0000",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

        <body className={poppins.className + " !min-h-screen"}>
        <Providers>
            <Layout className={'!min-h-screen text-white'}>
                {children}
            </Layout>
        </Providers>
        </body>
        </html>
    );
}
