import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import {Layout} from "antd";


const poppins = Poppins({subsets: ["latin"], weight: ["300", "400", "500", "600", "700"]});

export const metadata: Metadata = {
    title: "Bulldog",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <meta name={"viewport"} content={"width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"}/>
        </head>
        <body className={poppins.className + " !min-h-[calc(100dvh)]"}>
        <Providers>
            <Layout className={'!min-h-[calc(100dvh)] text-white'}>
                {children}
            </Layout>
        </Providers>
        </body>
        </html>
    );
}
